steps:
  - name: Checkout repository
    uses: actions/checkout@v2
  
  - name: Setup GitHub token
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    run: |
      git config --global user.name "GitHub Actions"
      git config --global user.email "github-actions[bot]@users.noreply.github.com"
  
  - name: Deploy to GitHub Pages
    uses: peaceiris/actions-gh-pages@v3
    with:
      personal_token: ${{ secrets.GH_TOKEN }}
